type Normal_Conveyor = 'CONVEYOR BELT UP' | 'CONVEYOR BELT DOWN' | 'CONVEYOR BELT LEFT' | 'CONVEYOR BELT RIGHT';
type Express_Conveyor = 'EXPRESS CONVEYOR BELT UP' | 'EXPRESS CONVEYOR BELT DOWN' | 'EXPRESS CONVEYOR BELT LEFT' | 'EXPRESS CONVEYOR BELT RIGHT';
type Site = 'REPAIR SITE' | 'DOUBLE REPAIR SITE';
type Wall = 'WALL LEFT' | 'WALL RIGHT' | 'WALL UP' | 'WALL DOWN' | 'CORNER WALL LEFT UP' | 'CORNER WALL LEFT DOWN' | 'CORNER WALL RIGHT DOWN' | 'CORNER WALL RIGHT UP';
type Gear = 'RED GEAR' | 'GREEN GEAR';

export type TileNames = 'OPEN FLOOR' | 'PIT' | 'LASER' | Normal_Conveyor | Express_Conveyor | Site | Wall | Gear;